name: umss_icassp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - configargparse=0.13.0
  - cudatoolkit=10.2.89
  - librosa=0.8.0
  - matplotlib=3.3.1
  - mir_eval=0.7
  - numpy=1.23.5
  - pandas=1.2.3
  - pillow=9.4.0
  - pip=23.2.1
  - pysoundfile=0.10.3
  - python=3.8.16
  - python-sounddevice=0.4.0
  - resampy=0.2.2
  - scikit-learn=1.3.0
  - scipy=1.5.2
  - tensorboard=2.3.0
  - torchaudio=0.6.0
  - pytorch=1.6.0
  - tqdm=4.49.0
  - pip:
      - nnaudio==0.3.2
      - pumpp==0.6.0